import AsyncStorage from '@react-native-async-storage/async-storage';
import * as RNLocalize from 'react-native-localize';

// Import JSON files (generated by syncTranslation script)
import enTranslations from '../googlesheetlocales/en.json';
import hiTranslations from '../googlesheetlocales/hi.json';
import arTranslations from '../googlesheetlocales/ar.json';

// No runtime CSV parsing; we only load JSON generated by syncTranslation

class GoogleSheetsI18n {
  constructor() {
    this.translations = {};
    this.currentLanguage = 'en';
    this.isReady = false;
  }

  // Load from JSON files (offline support)
  async loadTranslations() {
    try {
      // Load from JSON files first (generated by syncTranslation)
      this.translations = {
        en: enTranslations || {},
        hi: hiTranslations || {},
        ar: arTranslations || {},
      };

      // Load persisted language preference
      const cachedLang = await AsyncStorage.getItem('googleSheetsLanguage');
      if (cachedLang && (cachedLang === 'en' || cachedLang === 'hi' || cachedLang === 'ar')) {
        this.currentLanguage = cachedLang;
      } else {
        // Set default language from device
        const locales = RNLocalize.getLocales();
        const deviceLang = (Array.isArray(locales) && locales[0]?.languageCode) || 'en';
        const fallback = (deviceLang === 'hi' || deviceLang === 'ar') ? deviceLang : 'en';
        this.currentLanguage = fallback;
      }
      
      this.isReady = true;
      return true;
    } catch (error) {
      console.error('Failed to load JSON translations:', error);
      this.isReady = false;
      return false;
    }
  }

  // No network fetch here; use npm run syncTranslation to regenerate JSON files

  t(key, lang = null) {
    const langToUse = lang || this.currentLanguage;
    return this.translations[langToUse]?.[key] || this.translations.en?.[key] || key;
  }

  async changeLanguage(lang) {
    this.currentLanguage = lang;
    await AsyncStorage.setItem('googleSheetsLanguage', lang);
  }

  getCurrentLanguage() {
    return this.currentLanguage;
  }

  getAvailableLanguages() {
    return Object.keys(this.translations).filter(lang => 
      Object.keys(this.translations[lang] || {}).length > 0
    );
  }
}

const googleSheetsI18n = new GoogleSheetsI18n();

export default googleSheetsI18n;

